env: 2
runtime: python

manual_scaling:
  instances: 1

beta_settings:
  service_account_scopes: >
    https://www.googleapis.com/auth/cloud-platform

entrypoint: python -m googleclouddebugger -- randomgenerator.py
